#!/bin/sh /etc/rc.common

# Start after the network and dnsmasq
START=99

PROG=/srv/edgesec
CONFIG_FILE=/srv/config.ini
KEY=12345
LOG_FILE=/srv/edgesec.log

reload() {
    kill -SIGHUP `cat /var/run/edgesec.pid`
}

start() {
    $PROG -c $CONFIG_FILE -s $KEY -f $LOG_FILE -m -dddddddd
}

stop() {
    killall -q capsrv
    killall -q mdnsf
    kill -9 `cat /var/run/edgesec.pid`
}
