install(
  TARGETS edgesec capsrv
  RUNTIME DESTINATION "bin"
)
if (BUILD_REST_SERVER AND LIBMICROHTTPD_LIB)
  install(
    TARGETS restsrv
    RUNTIME DESTINATION "bin"
  )
endif ()
if (BUILD_SQLSYNC_SERVICE AND LIBSQLITE_LIB)
  install(
    TARGETS sqlsyncsrv
    RUNTIME DESTINATION "bin"
  )
endif ()
if (BUILD_REVERSE_SERVICE)
  install(
    TARGETS revclient revsrv
    RUNTIME DESTINATION "bin"
  )
endif ()

install(FILES "${PROJECT_BINARY_DIR}/config.ini" DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
if (BUILD_UUID_LIB AND LIBUUID_LIB)
  install(DIRECTORY ${LIBUUID_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_SQLITE_LIB AND LIBSQLITE_LIB)
  install(DIRECTORY ${LIBSQLITE_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if(BUILD_PCAP_LIB AND LIBPCAP_LIB)
  install(DIRECTORY ${LIBPCAP_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if(BUILD_OPENSSL_LIB AND LIBCRYPTO_LIB)
  install(DIRECTORY ${LIBOPENSSL_LIB_PATH} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_NETLINK_LIB AND LIBNETLINK_LIB)
  install(DIRECTORY ${LIBNETLINK_LIB_PATH} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_NDPI_LIB AND LIBNDPI_LIB)
  install(DIRECTORY ${LIBNDPI_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_MNL_LIB AND LIBMNL_LIB)
  install(DIRECTORY ${LIBMNL_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_MICROHTTPD_LIB AND LIBMICROHTTPD_LIB)
  install(DIRECTORY ${LIBMICROHTTPD_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_GRPC_LIB AND LIBGRPC_LIB)
  install(DIRECTORY ${LIBGRPC_LIB_DIR} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()

if (BUILD_HOSTAPD AND HOSTAPD)
  install(PROGRAMS ${HOSTAPD} DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")
endif ()
