task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      - image_family: freebsd-14-0-snap
      # - image_family: freebsd-13-1 # currently not working
  cmake_dependencies_cache:
    # cache CMake dependencies
    folder: ./build/dl
    fingerprint_script:
      - echo $CIRRUS_OS
      # lib/*.cmake files contains the dependencies that we use
      - cat lib/*.cmake
  install_script: |
    # autoconf/automake/pkgconf is required by sqlite
    # bison/libtool/gettext is required by util-linux (uuid library)
    pkg install -y cmake llvm git lcov autoconf automake bison libtool gettext pkgconf
  install_check_version_script: |
    llvm-cov gcov --version
    clang --version
  configure_script: |
    cmake --preset freebsd -DCONFIGURE_COVERAGE=BOOL:ON
  build_script: |
    cmake --build --preset freebsd --parallel "$(($(sysctl -n hw.ncpu) + 1))"
  env:
    # list of tests that are currently failing on FreeBSD
    FAILING_TESTS: test_edgesec test_dnsmasq test_mdns_service
  test_script: |
    ctest --preset freebsd --output-on-failure --output-junit junit-test-results.xml \
    || true # We look at junit XML output file for failures
  check_failing_tests_script: |
    # double-check that failing tests actually fail
    python -c "$CHECK_FAILING_TESTS" ./build/freebsd/junit-test-results.xml
  # test_with_coverage_script: |
  #   cmake --build --preset freebsd --parallel "$(($(sysctl -n hw.ncpu) + 1))" --target coverage
  # uploading coverage is currently a bit difficult
  # since the codecoverage uploader doesn't yet support FreeBSD

environment:
  # Script that loads a JUnit XML file generated from CTest,
  # (generated via `ctest --output-junit <file>`)
  # then checks to see if the list of failing tests is exactly the same as the
  # space separated list of tests in the `FAILING_TEST` environment variable.
  #
  # Example:
  #   FAILING_TESTS='test_a test_b' python3 -c "$CHECK_FAILING_TESTS" junit-test-results.xml
  CHECK_FAILING_TESTS: |
    #!/usr/bin/env python3
    import os

    expected_failing_tests=set(
      os.getenv("FAILING_TESTS").split(" ")
    )

    import sys
    import xml.etree.ElementTree as ET

    tree = ET.parse(sys.argv[1])
    root = tree.getroot()
    failing_tests = {
      testcase.get("name")
      for testcase in root.findall('testcase')
      if testcase.get("status") == "fail"
    }

    import unittest
    unittest.TestCase().assertSetEqual(
      expected_failing_tests,
      failing_tests,
      "❌ CTest failing tests do not match expected edgesec failing tests."
    )

    print("✅ CTest failing tests match expected edgesec failing tests.")
