# Configure script for hostapd
# Arguments
#   CFLAGS: Flags to pass the C compiler (e.g. include directives)
#   LIBS: Flags to pass to linker (e.g. linker directives)
#   BINDIR: Binary Directory to place hostapd bin

# Copies Alex's original configuration script
file(READ "${CMAKE_CURRENT_LIST_DIR}/hostap/hostapd/.config" original_config)
# Adds our new additions
file(WRITE ${INSTALL_CONFIG} "${original_config}
#autogenerated by cmake externalproject
CFLAGS+=${CFLAGS}
LIBS+=${LIBS}
BINDIR=${BINDIR}
")

