# Compile libmicrohttpd-0.9.72
if (BUILD_MICROHTTPD_LIB AND NOT (BUILD_ONLY_DOCS))
  set(LIBMICROHTTPD_SOURCE_DIR "${CMAKE_SOURCE_DIR}/lib/libmicrohttpd-0.9.72")
  set(LIBMICROHTTPD_INSTALL_ROOT "${CMAKE_CURRENT_BINARY_DIR}/lib")
  set(LIBMICROHTTPD_INSTALL_DIR "${LIBMICROHTTPD_INSTALL_ROOT}/libmicrohttpd")
  set(LIBMICROHTTPD_INCLUDE_DIR "${LIBMICROHTTPD_INSTALL_DIR}/include")
  set(LIBMICROHTTPD_LIB_DIR "${LIBMICROHTTPD_INSTALL_DIR}/lib")

  find_library(LIBMICROHTTPD_LIB NAMES microhttpd PATHS "${LIBMICROHTTPD_LIB_DIR}" NO_DEFAULT_PATH)
  if (LIBMICROHTTPD_LIB)
    message("Found libmicrohttpd library: ${LIBMICROHTTPD_LIB}")
  ELSE ()
    execute_process(COMMAND
      bash ${CMAKE_SOURCE_DIR}/lib/compile_microhttpd.sh
      ${LIBMICROHTTPD_SOURCE_DIR}
      ${LIBMICROHTTPD_INSTALL_ROOT}
      ${target_autoconf_triple}
    )
    find_library(LIBMICROHTTPD_LIB NAMES microhttpd PATHS "${LIBMICROHTTPD_LIB_DIR}" NO_DEFAULT_PATH)
  endif ()
endif ()
