# Compile libmicrohttpd-0.9.72
if (BUILD_MICROHTTPD_LIB AND NOT (BUILD_ONLY_DOCS))
  find_library(LIBMICROHTTPD_LIB NAMES microhttpd PATHS "${CMAKE_SOURCE_DIR}/lib/libmicrohttpd-0.9.72/build/lib" NO_DEFAULT_PATH)
  set(LIBMICROHTTPD_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/libmicrohttpd-0.9.72/build/include")
  if (LIBMICROHTTPD_LIB)
    message("Found libmicrohttpd library: ${LIBMICROHTTPD_LIB}")
  ELSE ()
    execute_process(COMMAND bash "${CMAKE_SOURCE_DIR}/lib/compile_libmicrohttpd.sh")
    find_library(LIBMICROHTTPD_LIB NAMES microhttpd PATHS "${CMAKE_SOURCE_DIR}/lib/libmicrohttpd-0.9.72/build/lib" NO_DEFAULT_PATH)
  endif ()
endif ()
