# Compile library libnetlink
if (BUILD_NETLINK_LIB AND NOT (BUILD_ONLY_DOCS))
  set(LIBNETLINK_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib/netlink")
  set(LIBNETLINK_INCLUDE_PATH "${LIBNETLINK_INSTALL_DIR}/include")
  set(LIBNETLINK_UAPI_INCLUDE_PATH "${LIBNETLINK_INCLUDE_PATH}/uapi")
  set(LIBNETLINK_LIB_PATH ${LIBNETLINK_INSTALL_DIR}/lib)
  find_library(LIBNETLINK_LIB NAMES libnetlink PATHS "${LIBNETLINK_LIB_PATH}" NO_DEFAULT_PATH)
  if (LIBNETLINK_LIB)
    message("Found libnetlink library: ${LIBNETLINK_LIB}")
  ELSE ()
    execute_process(COMMAND bash ${CMAKE_SOURCE_DIR}/lib/compile_libnetlink.sh ${CMAKE_CURRENT_BINARY_DIR}/lib ${CMAKE_C_COMPILER} ${CMAKE_CXX_COMPILER} )
    find_library(LIBNETLINK_LIB NAMES libnetlink PATHS "${LIBNETLINK_LIB_PATH}" NO_DEFAULT_PATH)
  endif ()
  find_library(LL_MAP_LIB NAMES ll_map PATHS "${LIBNETLINK_LIB_PATH}")
  message("Found ll_map library: ${LL_MAP_LIB}")
  find_library(UTILS_LIB NAMES utils PATHS "${LIBNETLINK_LIB_PATH}")
  message("Found utils library: ${UTILS_LIB}")
  find_library(RT_NAMES_LIB NAMES rt_names PATHS "${LIBNETLINK_LIB_PATH}")
  message("Found rt_names library: ${RT_NAMES_LIB}")
  find_library(LL_TYPES_LIB NAMES ll_types PATHS "${LIBNETLINK_LIB_PATH}")
  message("Found ll_types library: ${LL_TYPES_LIB}")
  find_library(LL_PROTO_LIB NAMES ll_proto PATHS "${LIBNETLINK_LIB_PATH}")
  message("Found ll_types library: ${LL_PROTO_LIB}")
endif ()
