# Compile libuuid-1.0.3
if (BUILD_UUID_LIB AND NOT (BUILD_ONLY_DOCS))
  set(LIBUUID_SOURCE_DIR "${CMAKE_SOURCE_DIR}/lib/libuuid-1.0.3")
  set(LIBUUID_INSTALL_ROOT "${CMAKE_CURRENT_BINARY_DIR}/lib")
  set(LIBUUID_INSTALL_DIR "${LIBUUID_INSTALL_ROOT}/uuid")
  set(LIBUUID_INCLUDE_DIR "${LIBUUID_INSTALL_DIR}/include")
  set(LIBUUID_LIB_DIR "${LIBUUID_INSTALL_DIR}/lib")

  find_library(LIBUUID_LIB NAMES uuid libuuid PATHS "${LIBUUID_LIB_DIR}" NO_DEFAULT_PATH)
  if (LIBUUID_LIB)
    message("Found libuuid library: ${LIBUUID_LIB}")
  ELSE ()
    execute_process(COMMAND bash ${CMAKE_SOURCE_DIR}/lib/compile_uuid.sh ${LIBUUID_SOURCE_DIR} ${LIBUUID_INSTALL_ROOT})
    find_library(LIBUUID_LIB NAMES uuid libuuid PATHS "${LIBUUID_LIB_DIR}" NO_DEFAULT_PATH)
  endif ()
endif ()
