/****************************************************************************
 * Copyright (C) 2020 by NQMCyber Ltd                                       *
 *                                                                          *
 * This file is part of EDGESec.                                            *
 *                                                                          *
 *   EDGESec is free software: you can redistribute it and/or modify it     *
 *   under the terms of the GNU Lesser General Public License as published  *
 *   by the Free Software Foundation, either version 3 of the License, or   *
 *   (at your option) any later version.                                    *
 *                                                                          *
 *   EDGESec is distributed in the hope that it will be useful,             *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Lesser General Public License for more details.                    *
 *                                                                          *
 *   You should have received a copy of the GNU Lesser General Public       *
 *   License along with EDGESec. If not, see <http://www.gnu.org/licenses/>.*
 ****************************************************************************/

/**
 * @file ename.h
 * @author Alexandru Mereacre
 * @brief error strings from errno.h include file.
 */

static char *ename[] = {
    /*   0 */ "",
    /*   1 */ "EPERM",
    "ENOENT",
    "ESRCH",
    "EINTR",
    "EIO",
    "ENXIO",
    /*   7 */ "E2BIG",
    "ENOEXEC",
    "EBADF",
    "ECHILD",
    /*  11 */ "EAGAIN/EWOULDBLOCK",
    "ENOMEM",
    "EACCES",
    "EFAULT",
    /*  15 */ "ENOTBLK",
    "EBUSY",
    "EEXIST",
    "EXDEV",
    "ENODEV",
    /*  20 */ "ENOTDIR",
    "EISDIR",
    "EINVAL",
    "ENFILE",
    "EMFILE",
    /*  25 */ "ENOTTY",
    "ETXTBSY",
    "EFBIG",
    "ENOSPC",
    "ESPIPE",
    /*  30 */ "EROFS",
    "EMLINK",
    "EPIPE",
    "EDOM",
    "ERANGE",
    /*  35 */ "EDEADLK/EDEADLOCK",
    "ENAMETOOLONG",
    "ENOLCK",
    "ENOSYS",
    /*  39 */ "ENOTEMPTY",
    "ELOOP",
    "",
    "ENOMSG",
    "EIDRM",
    "ECHRNG",
    /*  45 */ "EL2NSYNC",
    "EL3HLT",
    "EL3RST",
    "ELNRNG",
    "EUNATCH",
    /*  50 */ "ENOCSI",
    "EL2HLT",
    "EBADE",
    "EBADR",
    "EXFULL",
    "ENOANO",
    /*  56 */ "EBADRQC",
    "EBADSLT",
    "",
    "EBFONT",
    "ENOSTR",
    "ENODATA",
    /*  62 */ "ETIME",
    "ENOSR",
    "ENONET",
    "ENOPKG",
    "EREMOTE",
    /*  67 */ "ENOLINK",
    "EADV",
    "ESRMNT",
    "ECOMM",
    "EPROTO",
    /*  72 */ "EMULTIHOP",
    "EDOTDOT",
    "EBADMSG",
    "EOVERFLOW",
    /*  76 */ "ENOTUNIQ",
    "EBADFD",
    "EREMCHG",
    "ELIBACC",
    "ELIBBAD",
    /*  81 */ "ELIBSCN",
    "ELIBMAX",
    "ELIBEXEC",
    "EILSEQ",
    "ERESTART",
    /*  86 */ "ESTRPIPE",
    "EUSERS",
    "ENOTSOCK",
    "EDESTADDRREQ",
    /*  90 */ "EMSGSIZE",
    "EPROTOTYPE",
    "ENOPROTOOPT",
    /*  93 */ "EPROTONOSUPPORT",
    "ESOCKTNOSUPPORT",
    /*  95 */ "EOPNOTSUPP/ENOTSUP",
    "EPFNOSUPPORT",
    "EAFNOSUPPORT",
    /*  98 */ "EADDRINUSE",
    "EADDRNOTAVAIL",
    "ENETDOWN",
    "ENETUNREACH",
    /* 102 */ "ENETRESET",
    "ECONNABORTED",
    "ECONNRESET",
    "ENOBUFS",
    /* 106 */ "EISCONN",
    "ENOTCONN",
    "ESHUTDOWN",
    "ETOOMANYREFS",
    /* 110 */ "ETIMEDOUT",
    "ECONNREFUSED",
    "EHOSTDOWN",
    "EHOSTUNREACH",
    /* 114 */ "EALREADY",
    "EINPROGRESS",
    "ESTALE",
    "EUCLEAN",
    /* 118 */ "ENOTNAM",
    "ENAVAIL",
    "EISNAM",
    "EREMOTEIO",
    "EDQUOT",
    /* 123 */ "ENOMEDIUM",
    "EMEDIUMTYPE",
    "ECANCELED",
    "ENOKEY",
    /* 127 */ "EKEYEXPIRED",
    "EKEYREVOKED",
    "EKEYREJECTED",
    /* 130 */ "EOWNERDEAD",
    "ENOTRECOVERABLE",
    "ERFKILL",
    "EHWPOISON"};

#define MAX_ENAME 133
