/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dhcp.proto */

#ifndef PROTOBUF_C_dhcp_2eproto__INCLUDED
#define PROTOBUF_C_dhcp_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct Dhcp__DhcpSchema Dhcp__DhcpSchema;

/* --- enums --- */

/* --- messages --- */

struct Dhcp__DhcpSchema {
  ProtobufCMessage base;
  /*
   * Packet id
   */
  char *id;
  /*
   * Packet packet type
   */
  uint32_t op;
  /*
   * Packet type of hardware address for this machine (Ethernet, etc)
   */
  uint32_t htype;
  /*
   * Packet length of hardware address (of this machine)
   */
  uint32_t hlen;
  /*
   * Packet hops
   */
  uint32_t hops;
  /*
   * Packet random transaction id number - chosen by this machine
   */
  uint32_t xid;
  /*
   * Packet seconds used in timing
   */
  uint32_t secs;
  /*
   * Packet flags
   */
  uint32_t flags;
  /*
   * Packet IP address of this machine (if we already have one)
   */
  char *ciaddr;
  /*
   * Packet IP address of this machine (offered by the DHCP server)
   */
  char *yiaddr;
  /*
   * Packet IP address of DHCP server
   */
  char *siaddr;
  /*
   * Packet IP address of DHCP relay
   */
  char *giaddr;
  /*
   * Packet client ether MAC addr
   */
  char *chaddr;
};
#define DHCP__DHCP_SCHEMA__INIT                                                \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(&dhcp__dhcp_schema__descriptor)                    \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0,                    \
        (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string,      \
        (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string,      \
        (char *)protobuf_c_empty_string                                        \
  }

/* Dhcp__DhcpSchema methods */
void dhcp__dhcp_schema__init(Dhcp__DhcpSchema *message);
size_t dhcp__dhcp_schema__get_packed_size(const Dhcp__DhcpSchema *message);
size_t dhcp__dhcp_schema__pack(const Dhcp__DhcpSchema *message, uint8_t *out);
size_t dhcp__dhcp_schema__pack_to_buffer(const Dhcp__DhcpSchema *message,
                                         ProtobufCBuffer *buffer);
Dhcp__DhcpSchema *dhcp__dhcp_schema__unpack(ProtobufCAllocator *allocator,
                                            size_t len, const uint8_t *data);
void dhcp__dhcp_schema__free_unpacked(Dhcp__DhcpSchema *message,
                                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dhcp__DhcpSchema_Closure)(const Dhcp__DhcpSchema *message,
                                         void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dhcp__dhcp_schema__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_dhcp_2eproto__INCLUDED */
