/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dhcp.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dhcp.pb-c.h"
void   dhcp__dhcp_schema__init
                     (Dhcp__DhcpSchema         *message)
{
  static const Dhcp__DhcpSchema init_value = DHCP__DHCP_SCHEMA__INIT;
  *message = init_value;
}
size_t dhcp__dhcp_schema__get_packed_size
                     (const Dhcp__DhcpSchema *message)
{
  assert(message->base.descriptor == &dhcp__dhcp_schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dhcp__dhcp_schema__pack
                     (const Dhcp__DhcpSchema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dhcp__dhcp_schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dhcp__dhcp_schema__pack_to_buffer
                     (const Dhcp__DhcpSchema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dhcp__dhcp_schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dhcp__DhcpSchema *
       dhcp__dhcp_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dhcp__DhcpSchema *)
     protobuf_c_message_unpack (&dhcp__dhcp_schema__descriptor,
                                allocator, len, data);
}
void   dhcp__dhcp_schema__free_unpacked
                     (Dhcp__DhcpSchema *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dhcp__dhcp_schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dhcp__dhcp_schema__field_descriptors[13] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htype",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, htype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hlen",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, hlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hops",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, hops),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xid",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, xid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secs",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciaddr",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, ciaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yiaddr",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, yiaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "siaddr",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, siaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "giaddr",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, giaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chaddr",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dhcp__DhcpSchema, chaddr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dhcp__dhcp_schema__field_indices_by_name[] = {
  12,   /* field[12] = chaddr */
  8,   /* field[8] = ciaddr */
  7,   /* field[7] = flags */
  11,   /* field[11] = giaddr */
  3,   /* field[3] = hlen */
  4,   /* field[4] = hops */
  2,   /* field[2] = htype */
  0,   /* field[0] = id */
  1,   /* field[1] = op */
  6,   /* field[6] = secs */
  10,   /* field[10] = siaddr */
  5,   /* field[5] = xid */
  9,   /* field[9] = yiaddr */
};
static const ProtobufCIntRange dhcp__dhcp_schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor dhcp__dhcp_schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dhcp.DhcpSchema",
  "DhcpSchema",
  "Dhcp__DhcpSchema",
  "dhcp",
  sizeof(Dhcp__DhcpSchema),
  13,
  dhcp__dhcp_schema__field_descriptors,
  dhcp__dhcp_schema__field_indices_by_name,
  1,  dhcp__dhcp_schema__number_ranges,
  (ProtobufCMessageInit) dhcp__dhcp_schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
