/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dns.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dns.pb-c.h"
void dns__dns_schema__init(Dns__DnsSchema *message) {
  static const Dns__DnsSchema init_value = DNS__DNS_SCHEMA__INIT;
  *message = init_value;
}
size_t dns__dns_schema__get_packed_size(const Dns__DnsSchema *message) {
  assert(message->base.descriptor == &dns__dns_schema__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t dns__dns_schema__pack(const Dns__DnsSchema *message, uint8_t *out) {
  assert(message->base.descriptor == &dns__dns_schema__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t dns__dns_schema__pack_to_buffer(const Dns__DnsSchema *message,
                                       ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &dns__dns_schema__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
Dns__DnsSchema *dns__dns_schema__unpack(ProtobufCAllocator *allocator,
                                        size_t len, const uint8_t *data) {
  return (Dns__DnsSchema *)protobuf_c_message_unpack(
      &dns__dns_schema__descriptor, allocator, len, data);
}
void dns__dns_schema__free_unpacked(Dns__DnsSchema *message,
                                    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor == &dns__dns_schema__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor dns__dns_schema__field_descriptors[8] = {
    {
        "id", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Dns__DnsSchema, id), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "tid", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                            /* quantifier_offset */
        offsetof(Dns__DnsSchema, tid), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "flags", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                              /* quantifier_offset */
        offsetof(Dns__DnsSchema, flags), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "nqueries", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Dns__DnsSchema, nqueries), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "nanswers", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Dns__DnsSchema, nanswers), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "nauth", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                              /* quantifier_offset */
        offsetof(Dns__DnsSchema, nauth), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "nother", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                               /* quantifier_offset */
        offsetof(Dns__DnsSchema, nother), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "qname", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Dns__DnsSchema, qname), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned dns__dns_schema__field_indices_by_name[] = {
    2, /* field[2] = flags */
    0, /* field[0] = id */
    4, /* field[4] = nanswers */
    5, /* field[5] = nauth */
    6, /* field[6] = nother */
    3, /* field[3] = nqueries */
    7, /* field[7] = qname */
    1, /* field[1] = tid */
};
static const ProtobufCIntRange dns__dns_schema__number_ranges[1 + 1] = {{1, 0},
                                                                        {0, 8}};
const ProtobufCMessageDescriptor dns__dns_schema__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "dns.DnsSchema",
    "DnsSchema",
    "Dns__DnsSchema",
    "dns",
    sizeof(Dns__DnsSchema),
    8,
    dns__dns_schema__field_descriptors,
    dns__dns_schema__field_indices_by_name,
    1,
    dns__dns_schema__number_ranges,
    (ProtobufCMessageInit)dns__dns_schema__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
