/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dns.proto */

#ifndef PROTOBUF_C_dns_2eproto__INCLUDED
#define PROTOBUF_C_dns_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Dns__DnsSchema Dns__DnsSchema;


/* --- enums --- */


/* --- messages --- */

struct  Dns__DnsSchema
{
  ProtobufCMessage base;
  /*
   * Packet id
   */
  char *id;
  /*
   * Packet Transaction ID
   */
  uint32_t tid;
  /*
   * Packet Flags
   */
  uint32_t flags;
  /*
   * Packet Questions
   */
  uint32_t nqueries;
  /*
   * Packet Answers
   */
  uint32_t nanswers;
  /*
   * Packet Authority PRs
   */
  uint32_t nauth;
  /*
   * Packet Other PRs
   */
  uint32_t nother;
  /*
   * Packet question name
   */
  char *qname;
};
#define DNS__DNS_SCHEMA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dns__dns_schema__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string }


/* Dns__DnsSchema methods */
void   dns__dns_schema__init
                     (Dns__DnsSchema         *message);
size_t dns__dns_schema__get_packed_size
                     (const Dns__DnsSchema   *message);
size_t dns__dns_schema__pack
                     (const Dns__DnsSchema   *message,
                      uint8_t             *out);
size_t dns__dns_schema__pack_to_buffer
                     (const Dns__DnsSchema   *message,
                      ProtobufCBuffer     *buffer);
Dns__DnsSchema *
       dns__dns_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dns__dns_schema__free_unpacked
                     (Dns__DnsSchema *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dns__DnsSchema_Closure)
                 (const Dns__DnsSchema *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dns__dns_schema__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dns_2eproto__INCLUDED */
