/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: eth.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "eth.pb-c.h"
void eth__eth_schema__init(Eth__EthSchema *message) {
  static const Eth__EthSchema init_value = ETH__ETH_SCHEMA__INIT;
  *message = init_value;
}
size_t eth__eth_schema__get_packed_size(const Eth__EthSchema *message) {
  assert(message->base.descriptor == &eth__eth_schema__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t eth__eth_schema__pack(const Eth__EthSchema *message, uint8_t *out) {
  assert(message->base.descriptor == &eth__eth_schema__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t eth__eth_schema__pack_to_buffer(const Eth__EthSchema *message,
                                       ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &eth__eth_schema__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
Eth__EthSchema *eth__eth_schema__unpack(ProtobufCAllocator *allocator,
                                        size_t len, const uint8_t *data) {
  return (Eth__EthSchema *)protobuf_c_message_unpack(
      &eth__eth_schema__descriptor, allocator, len, data);
}
void eth__eth_schema__free_unpacked(Eth__EthSchema *message,
                                    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor == &eth__eth_schema__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor eth__eth_schema__field_descriptors[8] = {
    {
        "timestamp", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, timestamp), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "id", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, id), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "caplen", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                               /* quantifier_offset */
        offsetof(Eth__EthSchema, caplen), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "length", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                               /* quantifier_offset */
        offsetof(Eth__EthSchema, length), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ifname", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, ifname), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ether_dhost", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, ether_dhost), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ether_shost", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, ether_shost), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ether_type", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Eth__EthSchema, ether_type), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned eth__eth_schema__field_indices_by_name[] = {
    2, /* field[2] = caplen */
    5, /* field[5] = ether_dhost */
    6, /* field[6] = ether_shost */
    7, /* field[7] = ether_type */
    1, /* field[1] = id */
    4, /* field[4] = ifname */
    3, /* field[3] = length */
    0, /* field[0] = timestamp */
};
static const ProtobufCIntRange eth__eth_schema__number_ranges[1 + 1] = {{1, 0},
                                                                        {0, 8}};
const ProtobufCMessageDescriptor eth__eth_schema__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "eth.EthSchema",
    "EthSchema",
    "Eth__EthSchema",
    "eth",
    sizeof(Eth__EthSchema),
    8,
    eth__eth_schema__field_descriptors,
    eth__eth_schema__field_indices_by_name,
    1,
    eth__eth_schema__number_ranges,
    (ProtobufCMessageInit)eth__eth_schema__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
