/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: icmp6.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "icmp6.pb-c.h"
void   icmp6__icmp6_schema__init
                     (Icmp6__Icmp6Schema         *message)
{
  static const Icmp6__Icmp6Schema init_value = ICMP6__ICMP6_SCHEMA__INIT;
  *message = init_value;
}
size_t icmp6__icmp6_schema__get_packed_size
                     (const Icmp6__Icmp6Schema *message)
{
  assert(message->base.descriptor == &icmp6__icmp6_schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t icmp6__icmp6_schema__pack
                     (const Icmp6__Icmp6Schema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &icmp6__icmp6_schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t icmp6__icmp6_schema__pack_to_buffer
                     (const Icmp6__Icmp6Schema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &icmp6__icmp6_schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Icmp6__Icmp6Schema *
       icmp6__icmp6_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Icmp6__Icmp6Schema *)
     protobuf_c_message_unpack (&icmp6__icmp6_schema__descriptor,
                                allocator, len, data);
}
void   icmp6__icmp6_schema__free_unpacked
                     (Icmp6__Icmp6Schema *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &icmp6__icmp6_schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor icmp6__icmp6_schema__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Icmp6__Icmp6Schema, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp6_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Icmp6__Icmp6Schema, icmp6_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp6_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Icmp6__Icmp6Schema, icmp6_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp6_cksum",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Icmp6__Icmp6Schema, icmp6_cksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp6_un_data32",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Icmp6__Icmp6Schema, icmp6_un_data32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned icmp6__icmp6_schema__field_indices_by_name[] = {
  3,   /* field[3] = icmp6_cksum */
  2,   /* field[2] = icmp6_code */
  1,   /* field[1] = icmp6_type */
  4,   /* field[4] = icmp6_un_data32 */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange icmp6__icmp6_schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor icmp6__icmp6_schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "icmp6.Icmp6Schema",
  "Icmp6Schema",
  "Icmp6__Icmp6Schema",
  "icmp6",
  sizeof(Icmp6__Icmp6Schema),
  5,
  icmp6__icmp6_schema__field_descriptors,
  icmp6__icmp6_schema__field_indices_by_name,
  1,  icmp6__icmp6_schema__number_ranges,
  (ProtobufCMessageInit) icmp6__icmp6_schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
