/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ip6.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ip6.pb-c.h"
void ip6__ip6_schema__init(Ip6__Ip6Schema *message) {
  static const Ip6__Ip6Schema init_value = IP6__IP6_SCHEMA__INIT;
  *message = init_value;
}
size_t ip6__ip6_schema__get_packed_size(const Ip6__Ip6Schema *message) {
  assert(message->base.descriptor == &ip6__ip6_schema__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t ip6__ip6_schema__pack(const Ip6__Ip6Schema *message, uint8_t *out) {
  assert(message->base.descriptor == &ip6__ip6_schema__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t ip6__ip6_schema__pack_to_buffer(const Ip6__Ip6Schema *message,
                                       ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &ip6__ip6_schema__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
Ip6__Ip6Schema *ip6__ip6_schema__unpack(ProtobufCAllocator *allocator,
                                        size_t len, const uint8_t *data) {
  return (Ip6__Ip6Schema *)protobuf_c_message_unpack(
      &ip6__ip6_schema__descriptor, allocator, len, data);
}
void ip6__ip6_schema__free_unpacked(Ip6__Ip6Schema *message,
                                    ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor == &ip6__ip6_schema__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor ip6__ip6_schema__field_descriptors[8] = {
    {
        "id", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, id), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_un1_flow", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_un1_flow), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_un1_plen", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_un1_plen), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_un1_nxt", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_un1_nxt), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_un1_hlim", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_un1_hlim), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_un2_vfc", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_un2_vfc), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_src", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_src), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "ip6_dst", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING,
        0, /* quantifier_offset */
        offsetof(Ip6__Ip6Schema, ip6_dst), NULL, &protobuf_c_empty_string,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned ip6__ip6_schema__field_indices_by_name[] = {
    0, /* field[0] = id */
    7, /* field[7] = ip6_dst */
    6, /* field[6] = ip6_src */
    1, /* field[1] = ip6_un1_flow */
    4, /* field[4] = ip6_un1_hlim */
    3, /* field[3] = ip6_un1_nxt */
    2, /* field[2] = ip6_un1_plen */
    5, /* field[5] = ip6_un2_vfc */
};
static const ProtobufCIntRange ip6__ip6_schema__number_ranges[1 + 1] = {{1, 0},
                                                                        {0, 8}};
const ProtobufCMessageDescriptor ip6__ip6_schema__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "ip6.Ip6Schema",
    "Ip6Schema",
    "Ip6__Ip6Schema",
    "ip6",
    sizeof(Ip6__Ip6Schema),
    8,
    ip6__ip6_schema__field_descriptors,
    ip6__ip6_schema__field_indices_by_name,
    1,
    ip6__ip6_schema__number_ranges,
    (ProtobufCMessageInit)ip6__ip6_schema__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
