/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mdns.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mdns.pb-c.h"
void   mdns__mdns_schema__init
                     (Mdns__MdnsSchema         *message)
{
  static const Mdns__MdnsSchema init_value = MDNS__MDNS_SCHEMA__INIT;
  *message = init_value;
}
size_t mdns__mdns_schema__get_packed_size
                     (const Mdns__MdnsSchema *message)
{
  assert(message->base.descriptor == &mdns__mdns_schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mdns__mdns_schema__pack
                     (const Mdns__MdnsSchema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mdns__mdns_schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mdns__mdns_schema__pack_to_buffer
                     (const Mdns__MdnsSchema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mdns__mdns_schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mdns__MdnsSchema *
       mdns__mdns_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mdns__MdnsSchema *)
     protobuf_c_message_unpack (&mdns__mdns_schema__descriptor,
                                allocator, len, data);
}
void   mdns__mdns_schema__free_unpacked
                     (Mdns__MdnsSchema *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mdns__mdns_schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mdns__mdns_schema__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nqueries",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, nqueries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanswers",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, nanswers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nauth",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, nauth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nother",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, nother),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qname",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mdns__MdnsSchema, qname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mdns__mdns_schema__field_indices_by_name[] = {
  2,   /* field[2] = flags */
  0,   /* field[0] = id */
  4,   /* field[4] = nanswers */
  5,   /* field[5] = nauth */
  6,   /* field[6] = nother */
  3,   /* field[3] = nqueries */
  7,   /* field[7] = qname */
  1,   /* field[1] = tid */
};
static const ProtobufCIntRange mdns__mdns_schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor mdns__mdns_schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mdns.MdnsSchema",
  "MdnsSchema",
  "Mdns__MdnsSchema",
  "mdns",
  sizeof(Mdns__MdnsSchema),
  8,
  mdns__mdns_schema__field_descriptors,
  mdns__mdns_schema__field_indices_by_name,
  1,  mdns__mdns_schema__number_ranges,
  (ProtobufCMessageInit) mdns__mdns_schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
