/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sync.pb-c.h"
void   tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__init
                     (Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper         *message)
{
  static const Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper init_value = TDX__VOLT_API__SYNC__V1__PROTOBUF_LENGTH_PREFIX_WRAPPER__INIT;
  *message = init_value;
}
size_t tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *message)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *
       tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *)
     protobuf_c_message_unpack (&tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor,
                                allocator, len, data);
}
void   tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tdx__volt_api__sync__v1__protobuf_sync_wrapper__init
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper         *message)
{
  static const Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper init_value = TDX__VOLT_API__SYNC__V1__PROTOBUF_SYNC_WRAPPER__INIT;
  *message = init_value;
}
size_t tdx__volt_api__sync__v1__protobuf_sync_wrapper__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *message)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tdx__volt_api__sync__v1__protobuf_sync_wrapper__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tdx__volt_api__sync__v1__protobuf_sync_wrapper__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *
       tdx__volt_api__sync__v1__protobuf_sync_wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *)
     protobuf_c_message_unpack (&tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor,
                                allocator, len, data);
}
void   tdx__volt_api__sync__v1__protobuf_sync_wrapper__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__init
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration         *message)
{
  static const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration init_value = TDX__VOLT_API__SYNC__V1__PROTOBUF_SYNC_CONFIGURATION__INIT;
  *message = init_value;
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *
       tdx__volt_api__sync__v1__protobuf_sync_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *)
     protobuf_c_message_unpack (&tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor,
                                allocator, len, data);
}
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tdx__volt_api__sync__v1__protobuf_sync_configuration_header__init
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader         *message)
{
  static const Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader init_value = TDX__VOLT_API__SYNC__V1__PROTOBUF_SYNC_CONFIGURATION_HEADER__INIT;
  *message = init_value;
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration_header__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *message)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration_header__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration_header__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *
       tdx__volt_api__sync__v1__protobuf_sync_configuration_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *)
     protobuf_c_message_unpack (&tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor,
                                allocator, len, data);
}
void   tdx__volt_api__sync__v1__protobuf_sync_configuration_header__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__field_descriptors[1] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__field_indices_by_name[] = {
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tdx.volt_api.sync.v1.ProtobufLengthPrefixWrapper",
  "ProtobufLengthPrefixWrapper",
  "Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper",
  "tdx.volt_api.sync.v1",
  sizeof(Tdx__VoltApi__Sync__V1__ProtobufLengthPrefixWrapper),
  1,
  tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__field_descriptors,
  tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__field_indices_by_name,
  1,  tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__number_ranges,
  (ProtobufCMessageInit) tdx__volt_api__sync__v1__protobuf_length_prefix_wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tdx__volt_api__sync__v1__protobuf_sync_wrapper__field_descriptors[3] =
{
  {
    "header_index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper, header_lookup_case),
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper, header_index),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper, header_lookup_case),
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper, header_id),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tdx__volt_api__sync__v1__protobuf_sync_wrapper__field_indices_by_name[] = {
  1,   /* field[1] = header_id */
  0,   /* field[0] = header_index */
  2,   /* field[2] = payload */
};
static const ProtobufCIntRange tdx__volt_api__sync__v1__protobuf_sync_wrapper__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_sync_wrapper__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tdx.volt_api.sync.v1.ProtobufSyncWrapper",
  "ProtobufSyncWrapper",
  "Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper",
  "tdx.volt_api.sync.v1",
  sizeof(Tdx__VoltApi__Sync__V1__ProtobufSyncWrapper),
  3,
  tdx__volt_api__sync__v1__protobuf_sync_wrapper__field_descriptors,
  tdx__volt_api__sync__v1__protobuf_sync_wrapper__field_indices_by_name,
  1,  tdx__volt_api__sync__v1__protobuf_sync_wrapper__number_ranges,
  (ProtobufCMessageInit) tdx__volt_api__sync__v1__protobuf_sync_wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_proto",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, message_proto),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, message_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tdx__volt_api__sync__v1__protobuf_sync_configuration__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = message_name */
  1,   /* field[1] = message_proto */
  3,   /* field[3] = table_name */
};
static const ProtobufCIntRange tdx__volt_api__sync__v1__protobuf_sync_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tdx.volt_api.sync.v1.ProtobufSyncConfiguration",
  "ProtobufSyncConfiguration",
  "Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration",
  "tdx.volt_api.sync.v1",
  sizeof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration),
  4,
  tdx__volt_api__sync__v1__protobuf_sync_configuration__field_descriptors,
  tdx__volt_api__sync__v1__protobuf_sync_configuration__field_indices_by_name,
  1,  tdx__volt_api__sync__v1__protobuf_sync_configuration__number_ranges,
  (ProtobufCMessageInit) tdx__volt_api__sync__v1__protobuf_sync_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration_header__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "configuration",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader, n_configuration),
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader, configuration),
    &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum_message_size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader, maximum_message_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tdx__volt_api__sync__v1__protobuf_sync_configuration_header__field_indices_by_name[] = {
  1,   /* field[1] = configuration */
  0,   /* field[0] = id */
  2,   /* field[2] = maximum_message_size */
};
static const ProtobufCIntRange tdx__volt_api__sync__v1__protobuf_sync_configuration_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tdx.volt_api.sync.v1.ProtobufSyncConfigurationHeader",
  "ProtobufSyncConfigurationHeader",
  "Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader",
  "tdx.volt_api.sync.v1",
  sizeof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfigurationHeader),
  3,
  tdx__volt_api__sync__v1__protobuf_sync_configuration_header__field_descriptors,
  tdx__volt_api__sync__v1__protobuf_sync_configuration_header__field_indices_by_name,
  1,  tdx__volt_api__sync__v1__protobuf_sync_configuration_header__number_ranges,
  (ProtobufCMessageInit) tdx__volt_api__sync__v1__protobuf_sync_configuration_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
