/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sync.pb-c.h"
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__init
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration         *message)
{
  static const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration init_value = TDX__VOLT_API__SYNC__V1__PROTOBUF_SYNC_CONFIGURATION__INIT;
  *message = init_value;
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *
       tdx__volt_api__sync__v1__protobuf_sync_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *)
     protobuf_c_message_unpack (&tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor,
                                allocator, len, data);
}
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration__field_descriptors[4] =
{
  {
    "message_proto",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, message_proto),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, message_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum_message_size",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration, maximum_message_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tdx__volt_api__sync__v1__protobuf_sync_configuration__field_indices_by_name[] = {
  3,   /* field[3] = maximum_message_size */
  1,   /* field[1] = message_name */
  0,   /* field[0] = message_proto */
  2,   /* field[2] = table_name */
};
static const ProtobufCIntRange tdx__volt_api__sync__v1__protobuf_sync_configuration__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tdx.volt_api.sync.v1.ProtobufSyncConfiguration",
  "ProtobufSyncConfiguration",
  "Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration",
  "tdx.volt_api.sync.v1",
  sizeof(Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration),
  4,
  tdx__volt_api__sync__v1__protobuf_sync_configuration__field_descriptors,
  tdx__volt_api__sync__v1__protobuf_sync_configuration__field_indices_by_name,
  2,  tdx__volt_api__sync__v1__protobuf_sync_configuration__number_ranges,
  (ProtobufCMessageInit) tdx__volt_api__sync__v1__protobuf_sync_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
