/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wrapper.proto */

#ifndef PROTOBUF_C_wrapper_2eproto__INCLUDED
#define PROTOBUF_C_wrapper_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Wrapper__WrapperSchema Wrapper__WrapperSchema;


/* --- enums --- */

typedef enum _Wrapper__WrapperSchemaType {
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_UNSPECIFIED = 0,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ETH = 1,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ARP = 2,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_IP4 = 3,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_IP6 = 4,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ICMP4 = 5,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ICMP6 = 6,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_TCP = 7,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_UDP = 8,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_DNS = 9,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_MDNS = 10,
  WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_DHCP = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WRAPPER__WRAPPER_SCHEMA_TYPE)
} Wrapper__WrapperSchemaType;

/* --- messages --- */

struct  Wrapper__WrapperSchema
{
  ProtobufCMessage base;
  /*
   * The wrapper schema type
   */
  Wrapper__WrapperSchemaType type;
  /*
   * The attached message serialised
   */
  ProtobufCBinaryData message;
};
#define WRAPPER__WRAPPER_SCHEMA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wrapper__wrapper_schema__descriptor) \
    , WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_UNSPECIFIED, {0,NULL} }


/* Wrapper__WrapperSchema methods */
void   wrapper__wrapper_schema__init
                     (Wrapper__WrapperSchema         *message);
size_t wrapper__wrapper_schema__get_packed_size
                     (const Wrapper__WrapperSchema   *message);
size_t wrapper__wrapper_schema__pack
                     (const Wrapper__WrapperSchema   *message,
                      uint8_t             *out);
size_t wrapper__wrapper_schema__pack_to_buffer
                     (const Wrapper__WrapperSchema   *message,
                      ProtobufCBuffer     *buffer);
Wrapper__WrapperSchema *
       wrapper__wrapper_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wrapper__wrapper_schema__free_unpacked
                     (Wrapper__WrapperSchema *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Wrapper__WrapperSchema_Closure)
                 (const Wrapper__WrapperSchema *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    wrapper__wrapper_schema_type__descriptor;
extern const ProtobufCMessageDescriptor wrapper__wrapper_schema__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_wrapper_2eproto__INCLUDED */
