/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wrapper.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "wrapper.pb-c.h"
void   wrapper__wrapper_schema__init
                     (Wrapper__WrapperSchema         *message)
{
  static const Wrapper__WrapperSchema init_value = WRAPPER__WRAPPER_SCHEMA__INIT;
  *message = init_value;
}
size_t wrapper__wrapper_schema__get_packed_size
                     (const Wrapper__WrapperSchema *message)
{
  assert(message->base.descriptor == &wrapper__wrapper_schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wrapper__wrapper_schema__pack
                     (const Wrapper__WrapperSchema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wrapper__wrapper_schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wrapper__wrapper_schema__pack_to_buffer
                     (const Wrapper__WrapperSchema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wrapper__wrapper_schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wrapper__WrapperSchema *
       wrapper__wrapper_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wrapper__WrapperSchema *)
     protobuf_c_message_unpack (&wrapper__wrapper_schema__descriptor,
                                allocator, len, data);
}
void   wrapper__wrapper_schema__free_unpacked
                     (Wrapper__WrapperSchema *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wrapper__wrapper_schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wrapper__wrapper_schema__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Wrapper__WrapperSchema, type),
    &wrapper__wrapper_schema_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Wrapper__WrapperSchema, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wrapper__wrapper_schema__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange wrapper__wrapper_schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wrapper__wrapper_schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wrapper.WrapperSchema",
  "WrapperSchema",
  "Wrapper__WrapperSchema",
  "wrapper",
  sizeof(Wrapper__WrapperSchema),
  2,
  wrapper__wrapper_schema__field_descriptors,
  wrapper__wrapper_schema__field_indices_by_name,
  1,  wrapper__wrapper_schema__number_ranges,
  (ProtobufCMessageInit) wrapper__wrapper_schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue wrapper__wrapper_schema_type__enum_values_by_number[12] =
{
  { "WRAPPER_SCHEMA_UNSPECIFIED", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_UNSPECIFIED", 0 },
  { "WRAPPER_SCHEMA_ETH", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ETH", 1 },
  { "WRAPPER_SCHEMA_ARP", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ARP", 2 },
  { "WRAPPER_SCHEMA_IP4", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_IP4", 3 },
  { "WRAPPER_SCHEMA_IP6", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_IP6", 4 },
  { "WRAPPER_SCHEMA_ICMP4", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ICMP4", 5 },
  { "WRAPPER_SCHEMA_ICMP6", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_ICMP6", 6 },
  { "WRAPPER_SCHEMA_TCP", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_TCP", 7 },
  { "WRAPPER_SCHEMA_UDP", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_UDP", 8 },
  { "WRAPPER_SCHEMA_DNS", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_DNS", 9 },
  { "WRAPPER_SCHEMA_MDNS", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_MDNS", 10 },
  { "WRAPPER_SCHEMA_DHCP", "WRAPPER__WRAPPER_SCHEMA_TYPE__WRAPPER_SCHEMA_DHCP", 11 },
};
static const ProtobufCIntRange wrapper__wrapper_schema_type__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex wrapper__wrapper_schema_type__enum_values_by_name[12] =
{
  { "WRAPPER_SCHEMA_ARP", 2 },
  { "WRAPPER_SCHEMA_DHCP", 11 },
  { "WRAPPER_SCHEMA_DNS", 9 },
  { "WRAPPER_SCHEMA_ETH", 1 },
  { "WRAPPER_SCHEMA_ICMP4", 5 },
  { "WRAPPER_SCHEMA_ICMP6", 6 },
  { "WRAPPER_SCHEMA_IP4", 3 },
  { "WRAPPER_SCHEMA_IP6", 4 },
  { "WRAPPER_SCHEMA_MDNS", 10 },
  { "WRAPPER_SCHEMA_TCP", 7 },
  { "WRAPPER_SCHEMA_UDP", 8 },
  { "WRAPPER_SCHEMA_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor wrapper__wrapper_schema_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "wrapper.WrapperSchemaType",
  "WrapperSchemaType",
  "Wrapper__WrapperSchemaType",
  "wrapper",
  12,
  wrapper__wrapper_schema_type__enum_values_by_number,
  12,
  wrapper__wrapper_schema_type__enum_values_by_name,
  1,
  wrapper__wrapper_schema_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
