/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync.proto */

#ifndef PROTOBUF_C_sync_2eproto__INCLUDED
#define PROTOBUF_C_sync_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration;


/* --- enums --- */


/* --- messages --- */

struct  Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration
{
  ProtobufCMessage base;
  /*
   * The actual protobuf definition text.
   */
  char *message_proto;
  /*
   * The name of the message within `message_proto` above that represents the data to be synched.
   */
  char *message_name;
  /*
   * The name of the table within the target database.
   */
  char *table_name;
  /*
   * Optional maximum size of the serialised messages, this doesn't need to be exact and the default is 64K if omitted.
   */
  int32_t maximum_message_size;
};
#define TDX__VOLT_API__SYNC__V1__PROTOBUF_SYNC_CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/* Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration methods */
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__init
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration         *message);
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__get_packed_size
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration   *message);
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration   *message,
                      uint8_t             *out);
size_t tdx__volt_api__sync__v1__protobuf_sync_configuration__pack_to_buffer
                     (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration   *message,
                      ProtobufCBuffer     *buffer);
Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *
       tdx__volt_api__sync__v1__protobuf_sync_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tdx__volt_api__sync__v1__protobuf_sync_configuration__free_unpacked
                     (Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration_Closure)
                 (const Tdx__VoltApi__Sync__V1__ProtobufSyncConfiguration *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tdx__volt_api__sync__v1__protobuf_sync_configuration__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sync_2eproto__INCLUDED */
